# Generated by Django 2.2 on 2022-05-08 15:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='birth date')),
                ('city', models.CharField(blank=True, max_length=36, verbose_name='city')),
                ('email', models.EmailField(blank=True, max_length=30, verbose_name='email')),
                ('phone_number', models.CharField(blank=True, max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='telephone')),
                ('number_of_publications', models.PositiveIntegerField(default=0, editable=False, verbose_name='number of publications')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=2000, verbose_name='Post title')),
                ('post_content', models.TextField(verbose_name='Content')),
                ('publication_date', models.DateField(auto_now_add=True, verbose_name='Publication date')),
                ('editing_date', models.DateField(auto_now=True, verbose_name='Edit date')),
                ('is_published', models.BooleanField(default=True, verbose_name='Activity status')),
                ('status', models.CharField(choices=[('a', 'active'), ('no', 'not active')], default='no', max_length=1, verbose_name='Status')),
                ('post_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Post author')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'ordering': ['-publication_date'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='files/', verbose_name='Path')),
                ('post_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_ecommerce_store.Post', verbose_name='Post name')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
            },
        ),
    ]
