# Generated by Django 2.2 on 2022-05-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce_store', '0003_auto_20220509_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='number_of_publications',
        ),
        migrations.AddField(
            model_name='profile',
            name='deposit',
            field=models.PositiveIntegerField(default=0, verbose_name='Deposit'),
        ),
    ]
