# Generated by Django 2.2 on 2022-05-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce_store', '0005_auto_20220513_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_name', models.CharField(max_length=200, verbose_name='Promotion name')),
                ('promotion_description', models.CharField(max_length=2000, verbose_name='Promotion description')),
                ('promotion_creation_date', models.DateField(auto_now_add=True, verbose_name='Promotion creation date')),
            ],
            options={
                'verbose_name': 'promotion',
                'verbose_name_plural': 'promotions',
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
