# Generated by Django 2.2 on 2022-11-12 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce_store', '0006_auto_20220514_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='user',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
